### ISSUE TITLE
Raw tests seem to have extra conversions

### ISSUE THREAD

**Issue by jpark37** [sebbbi/perftest#19]
I'm seeing a lot of extra v_cvt_f32_u32 instructions comparing raw to structured tests. They go away if I wrap the raw loads with asfloat(). Did I make a mistake?

**Comment by sebbbi** [comment]
fixed. No measurable performance difference, since this test is mem bound not ALU bound.

**Comment by jpark37** [comment]
I haven't run the tool since filing this issue report, but my memory is that the timings were not identical. I can try again tonight just to make sure I'm not remembering wrong.

**Comment by jpark37** [comment]
I did Release build runs in this order: fast -> slow -> fast2 -> slow2

RTX 2080 Ti with SetStablePowerState utility running in background.

"ByteAddressBuffer.Load4 uniform" has the largest gap, 26.x ms -> 22.x ms, but there appear to be speed gains mostly across the board.

[raw_timings_2080ti.zip](https://github.com/sebbbi/perftest/files/5562769/raw_timings_2080ti.zip)

**Comment by sebbbi** [comment]
Oh yes. The uniform case can become faster, as Nvidia and Intel are using a trick to load them using wide vector loads and then shuffling the data to the inner loop. This trick reduces the load amount (in the 100% uniform case) by 32x on Nvidia GPU, thus the new bottleneck is ALU instead of memory operations. Thus the conversion operations actually cost something. 

In optimal case, you should be seeing 32x performance for uniform case in Nvidia and 8x on Intel. Hopefully this minor ALU optimization gets us closer to the theoretical limit.

**Comment by jpark37** [comment]
Without looking at the disassembly for the RTX 2080 Ti (does NVIDIA allow?), the raw loads do not seem to be doing a 32x uniform optimization. The typed loads seem to though:
Buffer<RGBA32f>.Load uniform: 1.931ms
Buffer<RGBA32f>.Load linear: 45.419ms
ByteAddressBuffer.Load4 uniform: 23.637ms
ByteAddressBuffer.Load4 linear: 60.374ms

The README mentions that the 2080 Ti is suspected to go through a direct path that doesn't have the optimization.

None of these tests should really be memory bound though, right? All the tests perform redundant loads within a 16 KB source buffer. The README says the tests operate within L1 cache, so it shouldn't be surprising to see gains for any of the raw load tests. I saw raw uniform speeding up the most, but some of the other raw tests seem to be slightly faster than just noise.
